[0m22:30:56.126863 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059cb5f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d453d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d45070>]}


============================== 22:30:56.144151 | aaf3b329-b4d7-4c3c-9807-c81a478aae82 ==============================
[0m22:30:56.144151 [info ] [MainThread]: Running with dbt=1.9.4
[0m22:30:56.144452 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mnd/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_training', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:30:56.188078 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/mnd/.dbt')}
[0m22:30:56.188295 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:30:56.189130 [debug] [MainThread]: Starter project path: /Users/mnd/.pyenv/versions/3.12.9/envs/dbt-training/lib/python3.12/site-packages/dbt/include/starter_project
[0m22:30:56.191501 [info ] [MainThread]: 
Your new dbt project "dbt_training" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:30:56.191653 [info ] [MainThread]: Setting up your profile.
[0m22:35:17.645522 [info ] [MainThread]: Profile dbt_training written to /Users/mnd/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:35:17.659307 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 261.5603, "process_in_blocks": "0", "process_kernel_time": 0.469323, "process_mem_max_rss": "237060096", "process_out_blocks": "0", "process_user_time": 2.948861}
[0m22:35:17.660760 [debug] [MainThread]: Command `dbt init` succeeded at 22:35:17.660615 after 261.56 seconds
[0m22:35:17.661400 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d2c7b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d2c58e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d1d3c50>]}
[0m22:35:17.662032 [debug] [MainThread]: Flushing usage events
[0m22:35:18.173821 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:36:22.763215 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1066cf890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a58ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a58890>]}


============================== 22:36:22.765482 | 463262a4-2036-468c-8a7d-0d3ca5cc8bd8 ==============================
[0m22:36:22.765482 [info ] [MainThread]: Running with dbt=1.9.4
[0m22:36:22.765778 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mnd/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:36:22.766063 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mnd/projects/dbt-training/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:36:22.767280 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.031534083, "process_in_blocks": "0", "process_kernel_time": 0.077224, "process_mem_max_rss": "99041280", "process_out_blocks": "0", "process_user_time": 0.572868}
[0m22:36:22.767510 [debug] [MainThread]: Command `dbt run` failed at 22:36:22.767470 after 0.03 seconds
[0m22:36:22.767681 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107dfbb90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a58bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a58c80>]}
[0m22:36:22.767835 [debug] [MainThread]: Flushing usage events
[0m22:36:23.226739 [debug] [MainThread]: An error was encountered while trying to flush usage events
